kind: Deployment
metadata:
  name: front-app
  namespace: default
spec:
  replicas: 2
  selector:
@@ -16,17 +17,17 @@ spec:
      - name: front-app
        image: containercluster.azurecr.io/frontend:30
        ports:
            - containerPort: 3000
        imagePullSecrets:
        - name: acr-secret 
        - containerPort: 3000
        env:
        - name: BASE_URL
          valueFrom: 
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: BASE_URL
        - name: DB_HOST
          valueFrom: 
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: DB_HOST
      imagePullSecrets:
      - name: acr-secret
